### ISSUE TITLE
Feature request - Zones as one secret

### ISSUE THREAD

**Issue by phdelodder** [alex3305/home-assistant-addons#16]
I'm trying out your addon and I'm stuck on the zones. Each of my zone has a latitude and longitude secret, to port it to bitwarden results in two login in bitwarden. 

Can there be a use a prefex in the name of the login eg zone - <name of the zone> and the custom fields are use for the latitude and longitude.

**Comment by alex3305** [comment]
Thanks for your feedback and using Bitwarden secrets add-on. For now you can use the `_username` and `_password` fields within Bitwarden to configure this. This is, obviously, not a neat solution but IMHO can do for now.

Since this feature request closely resembles #17, I will close this issue and continue discussion there.
