### ISSUE TITLE
What about Bitwarden secrets for ESPHome?

### ISSUE THREAD

**Issue by ArtKZ** [alex3305/home-assistant-addons#32]
Thank you for your add-on for Bitwarden secrets for Home Assistant!
Can you create a similar add-on for ESPHome?

**Comment by alex3305** [comment]
Hi @ArtKZ,

Thank you for creating this issue. At first thought, this would be a fantastic suggestion. Because it would be really easy to utilize the same file (contents) for both `secrets.yaml` files. However, I see one major drawback in this approach. Because you can view and edit your secrets in the ESPHome UI, your secrets would be exposed through the Home Assistant web interface. IMHO this would be a gaping security flaw.

That's why I would suggest that you create a secret file based on a Bitwarden Note as per the documentation. I have an example for a Google Assistant Service Key, but you can easily leverage this for ESPHome. Just create a note within Bitwarden called `esphome/secrets.yaml` and put in your secrets in YAML format, like so:

```yaml
wifi_ssid: 🍀 Random Words
wifi_password: CorrectHorseBatteryStaple
```

This add-on can and will overwrite the ESPHome `secrets.yaml` file and IMHO this would be a decent approach for this issue. Although I think that secrets should be massively overhauled from within Home Assistant (Supervisor) 🤷.  

Thanks! ❤️

**Comment by alex3305** [comment]
Hi @ArtKZ,

Since you didn't reply to my comment I'm going to assume this assessment is fine by you. That's why I'm going to close this issue for now. If you have any more input or feedback please don't hessitate to reply or open a new issue. Thank you ❤️.
